### ISSUE TITLE
[Request] Audio/Graphics/Video icons missing [for Ubuntu Studio/KXstudio]

### ISSUE THREAD

**Issue by lordekeen** [franksouza183/EvolvereSuit#112]
Hi, first of all thanks for the awesome icon set. Studio-orientated distros (like Ubuntu Studio) have a lot of uncommon audio/graphics/video apps installed, others not so uncommon but most of then dont have icons. Some dont need an exclusive icon, just a generic one they can share, like synthesizers and effects, so, here's my suggestions for icons (icons marked as general can be used in more than one software):
Audio:
- synthesizers (general)
- audio effects (general)
- patchage (visually manage connections between JACK aware softwares)
- sooperlooper (Looping Sampler)
- hydrogen (drum machine sequencer !important)
- lmms (linux midi sequencer)
- qtractor (midi sequencer in qt4)
- rosegarden (midi sequencer)
- internet dj console (live radio streaming)
- puredata (realtime computer music and graphics system)
- metronome (general)
- audio meter (general)
- audio plugins (general)
- hexter (yamaha midi plugin)
- jack-rack (effects rack for jack)
- autotalent (autotune)

Video/Graphics:
- Lightworks (professional NLE)
- Natron (open source composer, like Nuke)
- Alchemy (drawing software)

Extra
- trelby (screenplay editor)

**Comment by ghost** [comment]
Please make separate icon request issues per application. Provide the name, and attach official logo of application, if possible.

If some icons missing inside application, please provide screenshot pointing to that icon. And if possible, icon file name which application use for that icon(so we don't need to search it in their source code).

This will make things quite easier. Because in this state this issue **is** garbage. I'm sorry.

**Comment by ghost** [comment]
And yes, I know you are even forgotten about this, because it was about half-of-the-year passed by. But if @franksouza183 sometimes return to drawing icons, he will probably need ordered task list about what to draw, and how.
