### ISSUE TITLE
Icon request: PHPStorm

### ISSUE THREAD

**Issue by pofigoon** [franksouza183/EvolvereSuit#132]
Hello, thank you for such a great icon set. Absolutely brilliant!
It would be nice to have a PhpStorm icon in your set. 

The default one looks like this: http://www.macupdate.com/images/icons256/41146.png

Please feel free to ask if you need any help\testing

**Comment by migmolrod** [comment]
+1 to this.
I actually see there is a _'phpstorm.svg'_ in the _'evolvere/app/64'_ folder but is just the colored one, there is no monochrome version (ie, 24px or less).
If you want to use the included icon, you'll need to change it inside the `/usr/share/applications/jetbrains-phpstorm.desktop` (the desktop entry created by PHPStorm), since it's using the 'bin/webide.png' icon, bundled inside the PHPStorm tar.gz file.

I'm using Gnome 3.16 (Ubuntu Server 15.10 with Gnome added through `tasksel`), plus the _'Dash to dock'_ extension with an icon width of 24, so I mostly get the monochrome icons with few exceptions, which are coloured (like the PHPStorm icon). It's all I'm missing right now in this **amazing icon set**.

**Comment by ghost** [comment]
@franksouza183, there are you? People are waiting for you! Just do it already! :smile:

**Bring this project back to live!**

**Comment by franksouza183** [comment]
On new repo.
